version: "3.9"
services:
  gii_automation:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - FLASK_ENV=production
    env_file:
      - .env
    restart: always
