services:
  - type: web
    name: chrome-selenium-flask-app
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y wget gnupg2
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python app.py
